package cards;

public class UV {
    /**
     * Name of the UV that is generated by one of the functions generateName()
     */
    private final String name;
    /**
     * Corresponds to haw much the UV is worth
     */
    private final int credits;
    /**
     * Is used to know if the card is face down or not
     */
    private boolean visible;

    /**
     * This constructor take two arguments in parameter:
     * @param name is the name of the UV
     * @param credits is the number of credits that the UV is worth
     */
    public UV (String name,int credits) {
        this.name=name;
        this.credits=credits;
        this.visible=false;
    }
    public int getCredits () {
        return this.credits;
    }
    public boolean isVisible() {
        return this.visible;
    }

    /**
     * This method permits to make a card visible
     */
    public void makeVisible() {
        this.visible=true;
    }
    /**
     * This method permits to make a card not visible
     */
    public void hide() {
        this.visible=false;
    }

    /**
     * If the card is visible:
     * @return a String containing the name, the category and the number of credits of the card
     * If the card is not visible:
     * @return a String containing "XXXX"
     */
    public String toString() {
        if(isVisible()){
            return this.name+" ("+credits+" "+this.getClass().getSimpleName()+")";
        }else{
            return "XXXX";
        }
    }
}
